#!/bin/bash

DOTFILES_DIR=~/dotfiles
HOME_DIR=/home/victorsodre

echo -e "## Configurando Dotfiles..."

echo -e "\n* Linkando arquivos de configuração..."
sudo ln -fs /usr/local/bin $HOME_DIR/bin
ln -fs $DOTFILES_DIR/config-files/vim-rc $HOME_DIR/.vimrc
ln -fs $DOTFILES_DIR/config-files/terminator-config $HOME_DIR/.config/terminator/config

echo -e "\n* Copiando scripts para o ~/bin..."
sudo cp ./scripts/standby-screen $HOME_DIR/bin
sudo cp ./scripts/toggle-touchpad $HOME_DIR/bin

echo -e "\n* Atualizando i3 configurations..."
ln -fs $DOTFILES_DIR/i3/config $HOME_DIR/.i3/config
ln -fs $DOTFILES_DIR/i3/blocks $HOME_DIR/.i3/i3blocks

echo -e "\n## Procedimento finalizado"
